create table if not exists customers 
(
	id bigint generated by default as identity primary key,
	email text not null unique,
	display_name text not null,
	created_at timestamp not null default now()
);	

create table if not exists events
(
	id bigint generated by default as identity primary key,
	title text not null,
	starts_at timestamp not null,
	capacity int check (capacity > 0),
	price numeric(12, 2) check (price >= 0)
);

create table if not exists bookings 
(
	id bigint generated by default as identity primary key,
	customer_id bigint not null,
	created_at timestamp not null,
	status text check (status in ('pending', 'confirmed', 'cancelled')),
	constraint fk_bookings_customer_id
		foreign key (customer_id)
		references customers(id)
);

create table if not exists booking_items
(
	booking_id bigint not null,
	event_id bigint not null,
	ticket_count int check (ticket_count > 0),
	unit_price numeric(12, 2) check (unit_price >= 0),
	constraint pk_booking_items
		primary key (booking_id, event_id),
	constraint fk_booking_items_booking_id
		foreign key (booking_id)
		references bookings(id),
	constraint fk_booking_items_event_id
		foreign key (event_id)
		references events(id)
);